plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

keyed_groups:
  - key: tags.Name
    prefix: tag

filters:
  instance-state-name: running

hostnames:
  - tag:Name

compose:
  ansible_host: public_ip_address
  ansible_user: >
    {{
      'ec2-user' if (tags.get('Name') is defined and 'amazon' in tags.get('Name') | lower)
      else 'ubuntu'
    }}
